-----------------------------------------------------------------------------------------
KFinder, Version 1.0.0.0, Build 20180630
Copyright (C) 2018-2018 Jinliang Wang, Institute of Zoology, Zoological Society of London
Email: jinliang.wang@ioz.ac.uk
-----------------------------------------------------------------------------------------

Input file for KFinder: exampleInput.mac
Structure output file names in file: /Users/yuqingchen/Documents/Hare_Lab/CV_NYC_ddRAD/Kfinder_run/n380_all_cor/str.list
Number of sampled individuals: 380
Number of runs per K value: 10
Range of K values: [1, 4]

----------------------------------------------
   K  Mean_Ln(D|K)        DeltaK     Parsimony
----------------------------------------------
   1   -1732470.44             -        0.5000
   2   -1710924.08      556.0426        0.7680
   3   -1711229.00        2.1719        0.3322
   4   -1714128.66             -        0.4705

--------------------
    Method    Best_K
--------------------
    Evanno         2
 Pritchard         2
 Parsimony         2

------------------
Parsimony method:
------------------
  Best K = 2
  Best replicate run = 2
  Best output file = /Users/yuqingchen/Documents/Hare_Lab/CV_NYC_ddRAD/Kfinder_run/n380_all_cor/str_K2_rep1_f
